version: '3.9'

services:
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - '4040:4040'
    environment:
      - PYROSCOPE_LOG_LEVEL=debug

  cpp-resource-consuming:
    build: ./cpp_app
    ports:
      - '8080:8080'
    depends_on:
      - pyroscope

  java-resource-consuming:
    build: ./java_app
    depends_on:
      - pyroscope

  grafana-agent:
    image: 'grafana/alloy:latest'
    privileged: true
    user: root
    pid: host
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './config.alloy:/etc/alloy/config.alloy'
    ports:
      - '12345:12345'
    command:
      - run
      - /etc/alloy/config.alloy
      - '--storage.path=/tmp/alloy'
      - '--server.http.listen-addr=0.0.0.0:12345'
      - '--server.http.ui-path-prefix=/'
      - '--stability.level=public-preview'
    depends_on:
      - pyroscope
